language: node_js
node_js:
  - "6.10.3"
  - "8.10.0"
script:
  - npm run coverage
notifications:
  email: false
deploy:
  provider: npm
  email: engineering@zapier.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true
